version: '3.8'

services:
  # 1. Base de Datos MySQL
  base-datos:
    image: mysql:8.0
    container_name: mysql_tienda_local
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: DespachoSeguro2026
      MYSQL_DATABASE: tienda_despacho
    networks:
      - red-datos
    restart: always

  # 2. Microservicio de Ventas
  backend-ventas:
    build: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: spring_ventas_local
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://base-datos:3306/tienda_despacho?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: DespachoSeguro2026
    networks:
      - red-core
      - red-datos
    depends_on:
      - base-datos
    restart: always

  # 3. Microservicio de Despachos
  backend-despachos:
    build: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: spring_despachos_local
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://base-datos:3306/tienda_despacho?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: DespachoSeguro2026
    networks:
      - red-core
      - red-datos
    depends_on:
      - base-datos
    restart: always

  # 4. Frontend de la aplicación
  frontend-despacho:
    build: ./front_despacho
    container_name: web_despacho_local
    ports:
      - "80:80"
    networks:
      - red-core
    restart: always

networks:
  red-core:
    driver: bridge
  red-datos:
    driver: bridge