name: Despliegue automatico a AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Compilar, Subir a ECR y Desplegar en EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codigo local
      uses: actions/checkout@v3

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Iniciar sesion en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Construir y Subir Imagenes a Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        # 1. Backend de Ventas
        docker build -t $REGISTRY/ecr_repo_url_backend:ventas ./back-Ventas_SpringBoot/Springboot-API-REST
        docker push $REGISTRY/ecr_repo_url_backend:ventas

        # 2. Backend de Despachos
        docker build -t $REGISTRY/ecr_repo_url_backend:despachos ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker push $REGISTRY/ecr_repo_url_backend:despachos

        # 3. Frontend de Despacho
        docker build -t $REGISTRY/ecr_repo_url_frontend:latest ./front_despacho
        docker push $REGISTRY/ecr_repo_url_frontend:latest

    - name: Desplegar en la EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/proyecto_semestral
          
          # Inyectar credenciales del laboratorio directo en la sesion de SSH
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_SESSION_TOKEN="${{ secrets.AWS_SESSION_TOKEN }}"
          export AWS_DEFAULT_REGION="us-east-1"
          
          # Autenticar Docker con AWS ECR usando las variables recien inyectadas
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
          
          # Descargar las nuevas imagenes compiladas por GitHub
          docker-compose pull
          #gundam
          # Reiniciar los contenedores en segundo plano aplicando los cambios
          docker-compose up -d --remove-orphans